### PR TITLE
new patSignatureDecFunction fix

### PR DESCRIPTION
**Pull request by akashpopat**

### CODE REVIEW

**Comment by abhayjaiswal** [comment]
good work @akashpopat

**Comment by JmyW** [comment]
Thank you so much! You are great! @akashpopat

**Comment by darkjun99** [comment]
Thank you very much. @akashpopat

**Comment by QuocNamIT1** [comment]
I get an Exception when using this pattern  on Xamarin Android.
java.util.regex.PatternSyntaxException: Syntax error in regex pattern near index

**Pull request closed without merging**
