### PR TITLE
Update YouTubeExtractor.java

### PR DESCRIPTION
**Pull request by barisahmet**
Fix pattern.

### CODE REVIEW

**Comment by touficbatache** [comment]
Well, @HaarigerHarald still needs to accept this. What do you suggest to do in the meanwhile?

**Comment by barisahmet** [comment]
@touficbatache I am using my own fork in the meanwhile. You can do it as well.

**Comment by touficbatache** [comment]
@barisahmet How can I do that? I'm not really good with libraries 😅

**Comment by touficbatache** [comment]
Thankss!!

**Comment by HaarigerHarald** [comment]
It seems fine to me. Thanks

**Pull request merged**
