### PR TITLE
 Create not async version of extractor

### PR DESCRIPTION
**Pull request by otopba**
- Create not async version of extractor;
- Create new method extractFromVideoId(). This method need if I just want to get videoID and after that pass id to extractor.

### CODE REVIEW

**Comment by otopba** [comment]
@HaarigerHarald Hi!
Please create async version of this lib or approve this request. Thank you

**Comment by otopba** [comment]
@HaarigerHarald Hello!
Please check my PR. Thank you

**Comment by otopba** [comment]
@HaarigerHarald Hello!

**Comment by Arimionim** [comment]
@HaarigerHarald Hello! could you check it, please?

**Pull request closed without merging**
